version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: pipeline.log  # 可以被覆盖
    maxBytes: 10485760 # 10MB
    backupCount: 3
loggers:
  client:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  pipeline:
    level: INFO
    handlers: [file]
    propagate: no
root:
  level: INFO
  handlers: [console, file]